name: CI - Pest

on:
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: "8.4"

      - name: Composer Install
        run: composer install -q --no-interaction --no-progress

      - name: Dotenv
        run: cp .env.example .env

      - name: Key Generate
        run: php artisan key:generate

      - name: Run Pest
        run: php artisan test --compact
