name: CI - Pint

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: "8.4"
          php-extensions: "json, dom, curl, libxml, mbstring"

      - name: Run Pint
        run: ./vendor/bin/pint

      - name: Commit of Pint
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: CI - Pint Fixed
